language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
script:
  - coverage run --source=crudbuilder runtests.py
env:
  matrix:
   - DJANGO="Django<1.7"
   - DJANGO="Django<1.8"
   - DJANGO="Django<1.9"
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="Django<1.7"
    - python: "3.5"
      env: DJANGO="Django<1.8"
    # Django 1.9+ no longer supports python 3.2/3.3
    - python: "3.3"
      env: DJANGO="Django<1.9"

install:
  - pip install "$DJANGO" "coverage==3.7.1" coveralls "mock>=1.0.1"
after_success:
  coveralls