language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
script:
  - coverage run --source=crudbuilder runtests.py
env:
  matrix:
   - DJANGO="Django=1.7.8"
   - DJANGO="Django=1.8.2"
   - DJANGO="Django=1.9.2"
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="Django=1.7.8"
    # Django 1.9+ no longer supports python 3.2/3.3
    - python: "3.3"
      env: DJANGO="Django1.9.2"

install:
  - pip install -q Django==$DJANGO
  - python setup.py -q install
  - pip install django_tables2
  - pip install coveralls
after_success:
  coveralls